### PR TITLE
Converted everything to kotlin

### PR DESCRIPTION
**Pull request by indianpoptart**
This is the kotlin version of the app

### CODE REVIEW

**Comment by indianpoptart** [comment]
Also tackled a setting for #3

**Comment by indianpoptart** [comment]
I've tested on 2 devices, one on 8.0, and another on 9.0

Works great for me! I've released some apk's under my fork if you would like to try them

**Comment by indianpoptart** [comment]
Just added root support (Possibly, not tested by me) Thanks #6

**Comment by Cilenco** [comment]
Thanks, very nice work :)  I would like to test it before accepting it!
Can you move that to a development branch which I can accept then?

**Comment by indianpoptart** [comment]
around 200-300 kB extra (about 170 kB from the original APK on just kotlin changes, the rest are some additions)

**Pull request merged**
